version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*, pull_request_review_comment.*
    validate:
      - do: title
        must_include:
          regex: '.*'
          message: 'PR title must not be empty.'
      - do: description
        must_include:
          regex: '.*'
          message: 'PR description must not be empty.'
    pass:
      - do: merge
        method: merge
